### PR TITLE
TypeBox-Codegen

### PR DESCRIPTION
**Pull request by sinclairzx81**
This PR implements compiler support various reference models used in TB code generation. The options are `inline`, `ordered` and `cyclic` with the latter option used to express schematics representing mutual recursive types (specifically for ArkType code generation). The reference model can be configured by way of option on TypeScriptToTypeBox. The default is `inline`

```typescript
const code = TypeScriptToTypeBox.Generate('...', {
   referenceModel: 'cyclic' // default is 'inline'
})
```

### Inline
```typescript
const A = Type.Object({
  x: Type.String(),
})
const B = Type.Object({
  a: A // javascript reference
})
```
### Ordered
```typescript
const A = Type.Object({
  x: Type.String(),
}, { $id: 'A' })
const B = Type.Object({
  a: Type.Ref(A) // required A be topologically ordered first
})
```
### Cyclic
```typescript
const A = Type.Object({
  b: Type.Unsafe({ [Kind]: 'Ref', $ref: 'B' }) // synthetic reference
}, { $id: 'A' })
const B = Type.Object({
  a: Type.Unsafe({ [Kind]: 'Ref', $ref: 'A' }) // synthetic reference
})
```
PR also includes a new ArkType transform (very provisional and waiting on some features upstream)

### CODE REVIEW

**Comment by xddq** [comment]
@sinclairzx81 hey!

Sorry to bother, but did not want to create a separate issue for this one. Just to make sure, [ts2typebox](https://github.com/xddq/ts2typebox) is finally obsolete, isn't it? Will then just archive it and make it link to this repo instead.

**Comment by sinclairzx81** [comment]
@xddq Hi!

Hey, I don't think `ts2typebox` is obsolete as it's still providing a command line interface (and this project will only ever be a library), however, it could potentially be extended to support some of these other validation libraries if you're interested (so perhaps a rename?), maybe `ts2everything` ? 

There's still work to do on this project, have recently been eying up ProtoBuf IDL and GQL as next transform targets (and maybe a runtypes and myzod transforms), so could use some help getting those in order (also I'm not much of GQL user so could really use some insights getting an idea on what might be useful to generate for GQL users)

As for `ts2typebox`, I think it's worth keeping around as many users prefer to automate codegen via npm scripts :)

**Comment by xddq** [comment]
@sinclairzx81  Hey!

Alright, will keep it around then! Damn, ts2everything is an awesome name. You should create/own that package! : ]

I assume you mean GraphQL? I think GQL is rather [this](https://www.gqlstandards.org/). For GraphQL I could certainly help! As a first step I guess simple schema creation could be useful. As another one I guess custom scalars should be a good fit since the "basic" type system of GraphQL is somewhat limited (but can be extended via custom scalars).

Something cool/interesting at the later stages could be creating the resolvers. But I guess Typebox has no way to model functions types.. correct?

I will go ahead and do some research if people would even like Typescript to GraphQL. Will create an issue or discussion in this repo in the next couple of weeks on this.

**Comment by xddq** [comment]
@sinclairzx81 quick update, hope you are doing good!

1. ts2typebox (finally) uses the typebox-codegen package :]
2. I did not get to many responses when asking if typescript to GraphQL would be helpful. I think I would double down on that (until I see why it can be helpful/useful).

**Comment by sinclairzx81** [comment]
@xddq Hey, thanks for the update! :)

> I did not get to many responses when asking if typescript to GraphQL would be helpful. I think I would double down on that (until I see why it can be helpful/useful).

Yeah, still pondering how to approach GraphQL, ProtoBuf and SQL (DDL) (which is another thing I'm looking into). The problem mapping over to these targets is that the type systems for them are misaligned to the capabilities of TypeScript (so creating mappings for them usually requires losing something in the process). 

I do still think there's some merit to mapping them though (even if the developer needs to constrain types to those expressible in these targets) ... But it's tricky one as usually it's a case of being up against developer expectations while simultaneously being constrained by the thing being mapped into. 

That said, I did make a start on ProtoBuf (gRPC) IDL https://github.com/sinclairzx81/typebox-workbench/blob/main/src/codegen/model/model-to-grpc.ts which is 90% `UnsupportedType` :D Needs more work!!

Thanks again for the update. Currently letting the codegen package settle for a while before doing more work on it (and to give a few of the target libraries some time to update), Also it's great to hear `ts2typebox` is using the codegen package! :)

Cheers!
S

**Pull request merged**
